### ISSUE TITLE
How to run this tool? 

### ISSUE THREAD

**Issue by jolespin** [ablab/viralVerify#13]
Here's my version installed via pip: 

```
 viral_verify --version
viral_verify, version 0.1.1
```

Here's my command: 

```
viral_verify -i veba_output/binning/47-Drifterexpttime4punches_S40/tmp/unbinned.fasta -o veba_output/binning/47-Drifterexpttime4punches_S40/intermediate/viral_viralverify_output -H /usr/local/scratch/CORE/jespinoz/db/pfam/v33.1/Pfam-A.hmm.gz -t 16
```

Here's my log: 
```
[WARN] you may switch on flag -g/--remove-gaps to remove spaces
2021-08-10 19:51:36,718 INFO     Output file prefix not specified. Using input FASTA filename as prefix ("unbinned") [viral_verify.cli:main:61]
2021-08-10 19:51:36,718 INFO     Parsing contig sequences from "veba_output/binning/47-Drifterexpttime4punches_S40/tmp/unbinned.fasta" and determine if any could be circular [viral_verify.cli:main:63]
2021-08-10 19:51:37,038 INFO     Parsed 2 contigs from "veba_output/binning/47-Drifterexpttime4punches_S40/tmp/unbinned.fasta" [viral_verify.cli:main:65]
2021-08-10 19:51:37,038 INFO     Writing circularized contig sequences to "veba_output/binning/47-Drifterexpttime4punches_S40/intermediate/viral_viralverify_output/unbinned-circularized.fasta" [viral_verify.cli:main:67]
2021-08-10 19:51:37,042 INFO     Running Prodigal gene prediction on "veba_output/binning/47-Drifterexpttime4punches_S40/intermediate/viral_viralverify_output/unbinned-circularized.fasta" [viral_verify.cli:main:69]
2021-08-10 19:51:37,042 INFO     Running Prodigal gene prediction in metagenomic mode with command: prodigal -p meta -c -i veba_output/binning/47-Drifterexpttime4punches_S40/intermediate/viral_viralverify_output/unbinned-circularized.fasta -a veba_output/binning/47-Drifterexpttime4punches_S40/intermediate/viral_viralverify_output/unbinned-proteins.fa -o veba_output/binning/47-Drifterexpttime4punches_S40/intermediate/viral_viralverify_output/unbinned-genes.fa [viral_verify.prodigal:prodigal_meta:21]
2021-08-10 19:51:37,132 INFO     Ran Prodigal gene prediction outputting protein sequences to "veba_output/binning/47-Drifterexpttime4punches_S40/intermediate/viral_viralverify_output/unbinned-proteins.fa" and nucleotide sequences to  "veba_output/binning/47-Drifterexpttime4punches_S40/intermediate/viral_viralverify_output/unbinned-genes.fa". [viral_verify.prodigal:prodigal_meta:26]
2021-08-10 19:51:37,132 INFO     Prodigal protein sequence output at "veba_output/binning/47-Drifterexpttime4punches_S40/intermediate/viral_viralverify_output/unbinned-proteins.fa" [viral_verify.cli:main:75]
2021-08-10 19:51:37,132 INFO     Prodigal nucleotide sequence output at "veba_output/binning/47-Drifterexpttime4punches_S40/intermediate/viral_viralverify_output/unbinned-genes.fa" [viral_verify.cli:main:76]
2021-08-10 19:51:37,132 INFO     Filtering out genes predicted over the end of the expected end of each contig. Output at "veba_output/binning/47-Drifterexpttime4punches_S40/intermediate/viral_viralverify_output/unbinned-proteins-circularized.fa" [viral_verify.cli:main:79]
2021-08-10 19:51:37,136 INFO     Parsing HMM names and descriptions from "/usr/local/scratch/CORE/jespinoz/db/pfam/v33.1/Pfam-A.hmm.gz" [viral_verify.cli:main:82]
Traceback (most recent call last):
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/VEBA-binning_env/bin/viral_verify", line 8, in <module>
    sys.exit(main())
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/VEBA-binning_env/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/VEBA-binning_env/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/VEBA-binning_env/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/VEBA-binning_env/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/VEBA-binning_env/lib/python3.7/site-packages/viral_verify/cli.py", line 83, in main
    protein_name_to_desc = hmm_names_to_desc(hmm_db)
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/VEBA-binning_env/lib/python3.7/site-packages/viral_verify/io.py", line 175, in hmm_names_to_desc
    return {hmm_name(x): hmm_desc(x) for x in parse_hmms(hmm_path)}
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/VEBA-binning_env/lib/python3.7/site-packages/viral_verify/io.py", line 175, in <dictcomp>
    return {hmm_name(x): hmm_desc(x) for x in parse_hmms(hmm_path)}
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/VEBA-binning_env/lib/python3.7/site-packages/viral_verify/io.py", line 146, in parse_hmms
    for line in handle:
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/VEBA-binning_env/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
1
```

Should I be using the PFAM database or the [database from FigShare](https://figshare.com/s/f897d463b31a35ad7bf0)? 

Can you update the [Usage](https://github.com/ablab/viralVerify#usage) on your GitHub?

**Comment by mikeraiko** [comment]
That's funny - someone else forked this repo about a year ago, refactored and submitted to pypi as viral_verify (https://github.com/peterk87/viral_verify) . That's why the output and such is so different. Thanks for pointing that out!

Meanwhile, our current github version is awaiting approval for bioconda channel. As soon as that happens, I'll update accordingly.

**Comment by jolespin** [comment]
That is so weird. They also took the namespace too? 

What's the process like for getting something on bioconda?

**Comment by mikeraiko** [comment]
That's open source, after all...
Bioconda submission turned out to be pretty straightforward. Create recipe (yaml and build.sh files) with all metadata and dependencies, test and commit to bioconda recipes repository. https://bioconda.github.io/contributor/workflow.html
Then, after all CI tests, it needs ti be reviewed by someone of bioconda members. No idea how long it takes :)
github.com/bioconda/bioconda-recipes/pull/30186

**Comment by AndAvia** [comment]
> I'm working on an institute-wide pipeline for JCVI and had some trouble running your tool.
> 
> Here's my version installed via pip:
> 
> ```
>  viral_verify --version
> viral_verify, version 0.1.1
> ```
> 
> Here's my command:
> 
> ```
> viral_verify -i veba_output/binning/47-Drifterexpttime4punches_S40/tmp/unbinned.fasta -o veba_output/binning/47-Drifterexpttime4punches_S40/intermediate/viral_viralverify_output -H /usr/local/scratch/CORE/jespinoz/db/pfam/v33.1/Pfam-A.hmm -t 16
> ```
> 
> ### Edit: I had to decompress the PFAM database which was the error in the original post that I've edited since then.
> Should I be using the PFAM database or the [database from FigShare](https://figshare.com/s/f897d463b31a35ad7bf0)?
> 
> Can you update the [Usage](https://github.com/ablab/viralVerify#usage) on your GitHub?
> 
> This is the results output:
> 
> ```
> veba_output/binning/47-Drifterexpttime4punches_S40/intermediate/viral_viralverify_output/
> ├── classified-fasta-output
> │   ├── unbinned-chromosome.fasta
> │   └── unbinned-unclassified.fasta
> ├── unbinned-circularized.fasta
> ├── unbinned-genes.fa
> ├── unbinned-hmmsearch.domtblout
> ├── unbinned-hmmsearch.output
> ├── unbinned-proteins-circularized.fa
> ├── unbinned-proteins.fa
> └── unbinned-results.csv
> ```
> 
> I ran the version from GitHub on a differen tdataset and got the following output:
> 
> ```
> testing/viralverify_output/
> ├── oral_viruses_domtblout
> ├── oral_viruses_feature_table.txt
> ├── oral_viruses_genes.fa
> ├── oral_viruses_input_with_circ.fasta
> ├── oral_viruses_out_pfam
> ├── oral_viruses_prodigal.log
> ├── oral_viruses_proteins_circ.fa
> ├── oral_viruses_proteins.fa
> ├── oral_viruses_result_table.csv
> ├── Prediction_results_fasta
> │   ├── oral_viruses_chromosome.fasta
> │   ├── oral_viruses_plasmid.fasta
> │   ├── oral_viruses_plasmid_uncertain.fasta
> │   ├── oral_viruses_virus.fasta
> │   └── oral_viruses_virus_uncertain.fasta
> └── viralverify.log
> 
> 1 directory, 15 files
> ```
> 
> How come the output is so different between the pip and GitHub versions?

Hi there, so in the end which database did you use or is that one annotated out a bit more accurately.

**Comment by jolespin** [comment]
I use geNomad now.

**Comment by AndAvia** [comment]
> I use geNomad now.

All right, thanks.

**Comment by jolespin** [comment]
Apologies @AndAvia , I wrote that from my phone but should have given more context.  Here's the geNomad publication: https://www.nature.com/articles/s41587-023-01953-y and here's the GitHub: https://github.com/apcamargo/genomad

I developed a wrapper around geNomad for my "binning-viral" module (though, it doesn't really bin and more so identifies contigs that are viral) in my VEBA package.  Here's the publication for VEBA (https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gkae528/7697622) and here's the GitHub (https://github.com/jolepsin/veba). 

If you only want to perform viral analysis, I would recommend just using geNomad because VEBA has a lot of functionality in other modules (e.g., assembly w/ SPAdes, rnaSPAdes, Fly or eukaryotic binning/gene modeling, etc) and requires more dependencies/databases.

**Comment by AndAvia** [comment]
@jolespin Thank you so much for your patience in replying! I only need to do virus identification at the moment, because there are so many virus identification software, I'm going to use genomad, VIBRANT, virfinder, deepvirfinder, virsorter, virsorter2, ViralVerify and these, but you said that ViralVerify two databases have different results, and I don't know which database to choose.I had a chance to look at your VEBA, and I found it very impressive! Wishing you a wonderful day!

**Comment by Dmitry-Antipov** [comment]
Hi,
Since this tool was released in 2021 and didn't receive significant updates, I'd also recommend for checking newer alternatives. If you are still interested to run exactly viralVerify, I'd definitely retrain the db with the updated pfam-a and genbank viral/plasmid/chromosomal sequences
